name: CI
on:
  push:
    branches:
      - '**'
  pull_request:


jobs:
  test:
    runs-on: ubuntu-24.04

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --extra dev
          cp .env.example .env

      - name: Start db
        working-directory: backend/timescaledb-env
        run: docker compose up -d --wait

      - name: Run backend tests
        working-directory: backend
        run: uv run pytest

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test:ci
  linter:
    runs-on: ubuntu-24.04

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --extra dev
          cp .env.example .env

      - name: Run backend linter
        working-directory: backend
        run: |
          uv run ruff check . --fix
          git add .
          git commit -m "style: fix linting and formatting"
          git push
          uv run ruff format --check

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps

      - name: Run frontend linter
        working-directory: frontend
        run: npm run lint
